esphome:
  name: example
  platform: ESP8266
  board: d1_mini

logger:
api:
ota:

wifi: !include includes/wifi.yaml

output:
  - platform: esp8266_pwm
    pin: D2
    frequency: 120HZ
    id: J3_pwm

light:
  - platform: monochromatic
    output: J3_pwm
    name: J3
    id: J3
    effects:
      - lambda:
          name: No Publish
          update_interval: 1000ms
          lambda: |-
            auto call = id(J3)->turn_on();
            float remote = id(J3)->remote_values.get_brightness();
            esph_log_d(__FILE__, "brightness: %f", remote);
            call.set_brightness(remote * 0.5);
            call.set_transition_length(100);
            call.set_publish(false);
            call.set_save(false);
            call.set_state(true);
            call.perform();
      - lambda:
          name: Publish
          update_interval: 1000ms
          lambda: |-
            auto call = id(J3)->turn_on();
            float remote = id(J3)->remote_values.get_brightness();
            esph_log_d(__FILE__, "brightness: %f", remote);
            call.set_brightness(remote * 0.5);
            call.set_transition_length(100);
            call.set_publish(true);
            call.set_save(false);
            call.set_state(true);
            call.perform();
