- platform: gpio
  pin: D4
  id: "LED"
  inverted: true
- platform: esp8266_pwm
  pin: D1
  frequency: 120HZ
  id: J1_pwm
- platform: esp8266_pwm
  pin: D2
  frequency: 120HZ
  id: J2_pwm
- platform: esp8266_pwm
  pin: D6
  frequency: 120HZ
  id: J3_pwm
- platform: esp8266_pwm
  pin: D7
  frequency: 120HZ
  id: J4_pwm
